apiVersion: maestro.i-am-bee.com/v1alpha1
kind: Agent
metadata:
  name: openai-test-mcp-ollama
  labels:
    app: testapp_mcp_ollama
spec:
  model: llama3.1
  description: test
  instructions: You are a helpful agent. Respond to the users question, making use of any required tools
  framework: openai
  mode: local

