apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: maestro-deployment
  labels:
    app: mas-example
spec:
  template:
    metadata:
      labels:
        app: mas-example
    agents:
      - Search Arxiv
      - Intermediary
      - Filter
      - Summary
    prompt: "Run the fetch tool using this function call: fetch_arxiv_titles(topic='quantum', k=5):"
    steps:
      - name: Search Arxiv
        agent: Search Arxiv
      - name: Intermediary
        agent: Intermediary
      - name: Filter
        agent: Filter
      - name: Summary
        agent: Summary
