apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: maestro-deployment
  labels:
    app: activity-planner-demo
spec:
  template:
    metadata:
      labels:
        app: activity-planner-demo
    agents:
      - activity_planner.ActivityPlannerCrew.activity_crew
    prompt: Show me some activities to do in London in cold weather
    steps:
      - name: begin
        agent: activity_planner.ActivityPlannerCrew.activity_crew
