apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: maestro-deployment
  labels:
    app: mas-example
spec:
  template:
    metadata:
      labels:
        app: mas-example
    agents:
      - current-affairs
      - hot-or-not
    prompt: New York City
    steps:
      - name: current-affairs
        agent: current-affairs
      - name: hot-or-not
        agent: hot-or-not