apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta_agent_workflow
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: meta_agent_workflow
      labels:
        project: maestro-demo
    agents:
      - A NLP Agent Planner TEST
      - A Format Input Agent TEST
      - A Create Agent YAML TEST
    prompt: I want 4 agents in order to ultimately decide what activities I should do in a given location. First agent get the current temperature given a location, the second to compare that temperature with historical temperatures, then another agent to provide a list of activities if it's cold or conversely another agent to proivde a list of activities if it is hot.
    steps:
      - name: English Instructions to Prompt
        agent: A NLP Agent Planner TEST
      - name: Specify Agents for Agent Generation
        agent: A Format Input Agent TEST
      - name: Creating Agent YAML Workflow
        agent: A Create Agent YAML TEST