apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta_agent_workflow
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: meta_agent_workflow
      labels:
        project: maestro-demo
    agents:
      - Format Input Agent
      - Create Agent YAML
      - Create Workflow YAML
    prompt: |
            number of agents: 2
            agent1: weather_fetcher – Retrieves weather data for a given location using OpenMeteo.
            agent2: temperature_comparator – Compares the retrieved temperature with historical averages using OpenMeteo.
    steps:
      - name: Format Input
        agent: Format Input Agent
      - name: Create Agent YAML
        agent: Create Agent YAML
      - name: input
        input:
          prompt: |
                  Build a structured workflow using the workflow_schema tool as a reference.

                  I have two agents in agents.yaml:
                  weather_fetcher – Retrieves weather data for a given location using the OpenMeteo tool.
                  temperature_comparator – Compares the retrieved temperature with historical averages using OpenMeteo.

                  Requirements:

                  Ensure the workflow follows the workflow.schema.json format.
                  Each step must:
                  Reference a valid agent from agents.yaml.
                  Have a name that describes its function.
                  The final output should be a valid structured workflow in YAML format, please make it easily readble in a code block
          template: "{CONNECTOR}"
      - name: Create Workflow YAML
        agent: Create Workflow YAML