apiVersion: beehive/v1alpha1
kind: Agent
metadata:
  name: Search Arxiv
  labels:
    app: mas-example 
spec:
  model: llama3.1
  description: "Fetches the k most recent article titles from arXiv on a given topic."
  instructions: "Execute the given query using only the fetch tool provided. In your output, only list out the output the function gave you and nothing else. Example output: ['title1', 'title2', .... ]"  
  tools: 
    - 'fetch'
  code: |
        import urllib.request

        def fetch_arxiv_titles(topic: str, k: int = 10):
          """Fetches the k most recent article titles from arXiv on a given topic."""
          url = f"http://export.arxiv.org/api/query?search_query=all:{topic}&sortBy=submittedDate&sortOrder=descending&max_results={k}"

          with urllib.request.urlopen(url) as response:
              data = response.read().decode()

          titles = [line.split("<title>")[1].split("</title>")[0] for line in data.split("\n") if "<title>" in line][1:k+1]
          return titles

---
apiVersion: beehive/v1alpha1
kind: Agent
metadata:
  name: Individual Summary
  labels:
    app: mas-example
spec:
  model: llama3.1
  description: "creates a summary of the arxiv paper given a title"
  instructions: "You will be given the title of a research paper from ArXiv. Your task is to generate a detailed and confident summary of the core topics related to the title, even if the title is highly complex or abstract. You do not need to find the actual paper—just summarize the general subject area based on relevant knowledge. Do not include disclaimers such as 'I don't know' or 'It appears to be about.' Instead, provide a direct, authoritative explanation. If the title is highly technical, break it down into simpler components, explain each part clearly, and then summarize the overarching topic. The summary must be at least three paragraphs long and focus on key concepts, challenges, and potential applications."
  tools: 
    - 'llm'