# permissions for end users to view workflowruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: workflowrun-viewer-role
rules:
- apiGroups:
  - maestro.ai4quantum.com
  resources:
  - workflowruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maestro.ai4quantum.com
  resources:
  - workflowruns/status
  verbs:
  - get
