apiVersion: beehive/v1alpha1
kind: Workflow
metadata:
  name: beehive-deployment
  labels:
    app: mas-example
spec:
  strategy:
    type: sequence
    output: nonal
  template:
    metadata:
      labels:
        app: mas-example
    agents:
      - Search Arxiv
      - Intermediary
      - Filter
      - Individual Summary
    prompt: "Run the fetch tool using this function call: fetch_arxiv_titles(topic='quantum', k=5):"

