apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Search Arxiv
  labels:
    app: mas-example 
spec:
  model: llama3.1
  framework: beeai
  mode: remote
  description: "Fetches the k most recent article titles from arXiv on a given topic."
  instructions: "Execute the given query using only the fetch tool provided. In your output, only list out the output the function gave you and nothing else. Example output: ['title1', 'title2', .... ]"  
  tools: 
    - 'fetch'
  code: |
        import urllib.request

        def fetch_arxiv_titles(topic: str, k: int = 10):
          """Fetches the k most recent article titles from arXiv on a given topic."""
          url = f"http://export.arxiv.org/api/query?search_query=all:{topic}&sortBy=submittedDate&sortOrder=descending&max_results={k}"

          with urllib.request.urlopen(url) as response:
              data = response.read().decode()

          titles = [line.split("<title>")[1].split("</title>")[0] for line in data.split("\n") if "<title>" in line][1:k+1]
          return titles

---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Abstract Agent
  labels:
    app: mas-example 
spec:
  model: llama3.1
  framework: beeai
  mode: remote
  description: "Get the abstract of the desired paper."
  instructions: |
    "You will be given the title of a research paper from arXiv. First, use the arXiv tool to locate the paper by constructing a search_query with the paper title only.
    Once the paper is located, retrieve its summary, output the summary directly here."  
  tools: 
    - 'arxiv'

---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Summary Agent
  labels:
    app: mas-example 
spec:
  model: llama3.1
  framework: beeai
  mode: remote
  description: "Get the summary of the desired paper"
  instructions: |
    You will be given an abstract of a research paper. Your job is to expand on it and make sure the concept is more clear, try to make the summary very long and detailed. Please add onto the summary. Produce your final answer in a single block of text, without separating ‘Thought’ and ‘Result.’ Show everything directly in the final output.”
  tools: 
    - 'LLM'

---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Choose Paper
  labels:
    app: mas-example 
spec:
  model: llama3.1
  framework: beeai
  mode: remote
  description: "Choose a paper from the list of titles."
  instructions: |
    You will be given an abstract of a research paper. Your job is to expand on it and make sure the concept is more clear, try to make the summary very long and detailed. Please add onto the summary. Produce your final answer in a single block of text, without separating ‘Thought’ and ‘Result.’ Show everything directly in the final output.”
  tools: 
    - 'LLM'