apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Search Arxiv
  labels:
    app: mas-example 
spec:
  model: llama3.1
  description: "Fetches the k most recent article titles from arXiv on a given topic."
  instructions: "Execute the given query using only the fetch tool provided. In your output, only list out the output the function gave you and nothing else. Example output: ['title1', 'title2', .... ]"  
  tools: 
    - 'fetch'
  code: |
        import urllib.request

        def fetch_arxiv_titles(topic: str, k: int = 10):
          """Fetches the k most recent article titles from arXiv on a given topic."""
          url = f"http://export.arxiv.org/api/query?search_query=all:{topic}&sortBy=submittedDate&sortOrder=descending&max_results={k}"

          with urllib.request.urlopen(url) as response:
              data = response.read().decode()

          titles = [line.split("<title>")[1].split("</title>")[0] for line in data.split("\n") if "<title>" in line][1:k+1]
          return titles

---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Abstract Agent
  labels:
    app: mas-example 
spec:
  model: llama3.1
  description: "Fetches the k most recent article titles from arXiv on a given topic."
  instructions: |
    "You will be given the title of a research paper from arXiv. First, use the arXiv tool to locate the paper by constructing a search_query with the paper title only (do not include an "ids" field). For example, if the title is "Ergotropy-Based Quantum Thermodynamics", your input should be:
    { "search_query": { "include": [ { "field": "all", "value": "Ergotropy-Based Quantum Thermodynamics" } ] }, "start": 0, "maxResults": 1 }
    Once the paper is located and its abstract is retrieved, output the abstract directly here"  
  tools: 
    - 'arxiv'

---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Summary Agent
  labels:
    app: mas-example 
spec:
  model: llama3.1
  description: "Fetches the k most recent article titles from arXiv on a given topic."
  instructions: |
    You will be given an abstract of a research paper. Your job is to expand on it and make sure the concept is more clear, try to make the summary very long and detailed. Please add onto the summary. Produce your final answer in a single block of text, without separating ‘Thought’ and ‘Result.’ Show everything directly in the final output.”
  tools: 
    - 'LLM'