apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: summary-ai
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: summary-ai
      labels:
        project: maestro-demo
    agents:
      - Search Arxiv
      - Abstract Agent
      - Summary Agent
      - Choose Paper
    prompt: "Run the fetch tool using this function call: fetch_arxiv_titles(topic='quantum', k=5):"
    steps:
      - name: retreive papers
        agent: Search Arxiv
      - name: choose paper
        agent: Choose Paper
      - name: retrieve abstract 
        agent: Abstract Agent
      - name: get summary
        agent: Summary Agent