apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: summary-ai
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: summary-ai
      labels:
        project: maestro-demo
    agents:
      - Search Arxiv
      - Individual Summary
    prompt: "Run the fetch tool using this function call: fetch_arxiv_titles(topic='quantum', k=2):"
    steps:
      - name: retreive papers
        agent: Search Arxiv
      - name: create summary
        agent: Individual Summary