apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: summary-ai
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: summary-ai
      labels:
        project: maestro-demo
    agents:
      - Search Arxiv
      - Individual Summary
    prompt: "Run the fetch tool using this function call: fetch_arxiv_titles(topic='quantum', k=5):"
    steps:
      - name: Search Arxiv
        agent: Search Arxiv
      - name: input
        input: 
          prompt: "Here are the retrieved papers:\n{prompt}\n\nSelect the papers you want to summarize by entering the full title name (comma-separated):"
          template: "{response}"
      - name: Individual Summary
        agent: Individual Summary