apiVersion: maestro/v1
kind: Workflow
metadata:
  name: portfolio workflow
  labels:
    app: portfolio optimizer
spec:
  template:
    metadata:
      name: portfolio
      labels:
        app: portfolio
        use-case: portfolio
    agents:
        - stock
        - portfolio
        - plot
    #prompt: 8801.T, ITX.MC, META, GBPJPY, TMBMKDE, CLF, XS2239553048
    prompt: 8801.T, ITX.MC, META, GBPJPY=X, CLF
    steps:
      - name: stock
        agent: stock
      - name: portfolio
        agent: portfolio
      - name: plot
        agent: plot

