apiVersion: maestro/v1
kind: Workflow
metadata:
  name: portfolio workflow
  labels:
    app: portfolio optimizer
spec:
  template:
    metadata:
      name: portfolio
      labels:
        app: portfolio
        use-case: portfolio
    agents:
        - stock
        - portfolio
        - get security tickers
    prompt: meta,google,international business machines,iShares Core U.S. Aggregate Bond ETF
    steps:
      - name: step1
        agent: get security tickers

    # prompt: 8801.T, ITX.MC, META, GBPJPY=X, CLF
    # steps:
    #   - name: stock
    #     agent: stock
    #   - name: portfolio
    #     agent: portfolio

