apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: current-temperature
  labels:
    app: mas-example
spec:
  model: "llama3.1:latest"
  description: Get the current weather
  tools:
    - code_interpreter
    - weather
  instructions: An input is given of a location. Use the OpenMeteo tool to get today's current forecast for the location. Return results in the format - location, temperature in Fahrenheit, and date.
    Example output - New York City, 44.9째F, March 26, 2025

---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: hot-or-not
  labels:
    app: mas-example
spec:
  model: "llama3.1:latest"
  description: Is the current temperature hotter or colder than the historical monthly average.
  tools:
    - code_interpreter
    - weather
  instructions: Use the OpenMeteo weather tool to find the historical temperature of the given location. Determine if the input temperature is warmer or colder than the historical temperature.  Respond with hotter or colder and include the location name. 
    Example Input - New York City, 44.9째F, March 26, 2025
    Example output - The location is New York City, and the historical temperature was 56.3째F which is hotter than your input of 45.3째F.

---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: cold-activities
  labels:
    app: mas-example
spec:
  model: "llama3.1:latest"
  description: Find activities suited to do in the colder weather at a given location.
  tools:
    - code_interpreter
    - web_search
  instructions: The input a location that is currently colder than normal.  Perform a web search to find fun activities to do in the colder near the location and recommend five. Return these in bullet point format.
    Example Input -  'New York is colder' 
    Example Output - 'Go to a bar, go to the gym, go to the muesuem, visit Columbia, go to a club'
---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: hot-activities
  labels:
    app: mas-example
spec:
  model: "llama3.1:latest"
  description: Find activities suited to do in the hotter weather at a given location.
  tools:
    - code_interpreter
    - web_search
  instructions: The input a location that is currently hotter than normal.  Perform a web search to find fun activities to do in the hotter weather near the location and recommend five. Return these in bullet point format.
    Example Input - 'New York is hotter'
    Example Output - 'visit central park, go for a run, go to the muesuem, go for a swim, go get some pizza'
