apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: cbom.ai
  labels:
    app: cbom.ai
spec:
  template:
    metadata:
      labels:
        app: cbom.ai
    agents:
      - git fetcher
      - raw gh reader
      - identify post-quantum
      - component creator
      - BOM Assembler
      - selector agent
      - score
    prompt: |
      Use the git fetcher tool to get all the java files from the github repo where the owner is "Mastercard" and the repo is "client-encryption-java", and directly output its result. The output should be *ONLY* a list of URLs, and nothing else.
    steps:
    - name: step1
      agent: git fetcher
    - name: step1_score
      agent: score
      inputs: 
        - from: prompt
        - from: step1
      context: 
        - "A correct output should be a list of strings of raw GitHub URLs ending in .java from the Mastercard/client-encryption-java repo, with no extra text or formatting."
      output:
        - score_step1
    # - name: step2
    #   agent: selector agent
    # - name: step3
    #   agent: raw gh reader
    # - name: step4
    #   agent: identify post-quantum
    # - name: step5
    #   agent: component creator
    # - name: step6
    #   agent: BOM Assembler