name: Check Schema

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup poetry
        run: |
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install poetry
          poetry self add poetry-plugin-shell
      - name: Install dependencies
        run: |
          cd maestro
          poetry install
      - name: Check schema
        # Run from root to capture all projects - but poetry needs to run in maestro to pick up environment above
        run: |
          cd maestro
          poetry run sh -c 'cd .. && ci/check-schemas.sh'
