name: Maestro Tests
on:
  push:
    branches: [ 'main' ]
    paths:
    - 'maestro/**'
  pull_request:
    branches: [ 'main' ]
    paths:
    - 'maestro/**'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup poetry
        run: |
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install poetry
          poetry self add poetry-plugin-shell
      - name: Install dependencies
        run: |
          cd maestro
          poetry install
	  pip install beeai_framework
      - name: Run unit tests
        run: |
          cd maestro
          poetry run pytest --ignore=tests/integration/deploys
