name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        uv venv --python 3.12
        uv pip install -r requirements.txt
        uv pip install python-dotenv
        uv pip install crewai litellm==1.67.0.post1
        uv pip install -e .
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    - name: Run tests
      run: uv run pytest --ignore=tests/integration/deploys
