name: Test Workflow with Pip Install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: AI4quantum/maestro-demos
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Maestro
        run: pip install git+https://github.com/${{ github.repository }}.git@${{ github.ref }}
      - name: Create Agent
        run: maestro create workflows/simple/agents.yaml
      - name: Run Workflow
        run: maestro run workflows/simple/workflow.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
