name: Maestro Demo Smoke (Poetry + Ollama)
on:
  push:
    branches: [ 'main' ]
    paths:
      - '**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**'
      - '.github/workflows/**'
jobs:
  demo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python & Poetry
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry CLI
        run: |
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install poetry
          poetry self add poetry-plugin-shell
      - name: Bootstrap Maestro (deps + venv)
        shell: bash
        run: |
          chmod +x ./tools/setup_maestro.sh
          source ./tools/setup_maestro.sh
      - name: Smoke-test Poetry
        run: |
          poetry --version
          poetry show --no-dev

      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Smoke-test Ollama connectivity
        run: |
          ollama list
          echo '{"prompt":"Hello"}' | ollama run llama3.1:latest

