name: Maestro Operator Test
on:
  push:
    branches: [ "main" ]
    paths:
    - '**'
  pull_request:
    branches: [ "main" ]
    paths:
    - '**'
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd operator
        make docker-build
        make engine-docker-build
	docker tag docker.io/library/controller:latest localhost/controller:latest
	docker tag docker.io/library/maestro-engine:latest localhost/maestro-engine:latest
    - name: Install Kind
      run: |
        curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-$(uname)-amd64"
        chmod +x ./kind
        sudo mv kind /usr/local/bin
        which kind
    - name: Create Kind cluster
      run: |
        kind create cluster --config tests/integration/deploys/kind-config.yaml 
    - name: Load images cluster
      run: |
        kind load docker-image localhost/controller:latest 
        kind load docker-image localhost/maestro-engine:latest 
    - name: Install Maestro Operator
      run: |
        cd operator
        kubectl apply -f config/crd/bases
        make deploy
