name: Maestro Build and Upload Images

on:
  push:
    branches: [ maestroimages2 ]

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv and activate the environment
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Install dependencies
        run: |
          uv sync --all-extras
      - name: Build Maestro
        run: uv build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maestro-dist
          path: dist/*
      - name: Build and push the image
        run : |
          VERSION=$(grep -E '^(version|tool\.poetry\.version) *= *"[^"]+"' "pyproject.toml" | \
            head -n 1 | \
            sed -E 's/.*"([^"]+)".*/\1/')
          uv run tools/buidimg.sh	  
          docker login --username akihikokuroda --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io
          docker tag localhost/maestro-base:VERSION  ghcr.io/ai4quantum/maestro-base:$VERSION
          docker push ghcr.io/ai4quantum/maestro-base:$VERSION
          docker tag localhost/maestro-cli:VERSION  ghcr.io/ai4quantum/maestro-base:$VERSION
          docker push ghcr.io/ai4quantum/maestro-cli:$VERSION
