name: Maestro Demo Tests (ollama only)
on:
  push:
    branches: [ 'main' ]
    paths:
    - 'maestro/**'
  pull_request:
    branches: [ 'main' ]
    paths:
    - 'maestro/**'
    - '.github/workflows/**'
jobs:
  demo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup poetry
        run: |
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install poetry
          poetry self add poetry-plugin-shell
      - name: Install dependencies
        run: |
          cd maestro
          poetry install
      - name: Install Ollama
        uses: pydantic/ollama-action@v3
        with:
          # Small model - 7GB max in this runner
          model: llama3.1:latest
      - name: Run weather.ai workflow
        run: |
          cd maestro
          demos/workflows/weather-checker.ai/doctor.sh
          demos/workflows/weather-checker.ai/test.sh
        env:
          MAESTRO_DEMO_OLLAMA_MODEL: ollama/llama3.2:3b
      - name: Run summary.ai workflow
        run: |
          cd maestro
          demos/workflows/summary.ai/test_yaml/doctor.sh
          demos/workflows/summary.ai/test_yaml/test.sh
        env:
          MAESTRO_DEMO_OLLAMA_MODEL: ollama/llama3.2:3b