name: Maestro Tests
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install poetry
          poetry self add poetry-plugin-shell

      - name: Bootstrap Maestro (deps + venv)
        shell: bash
        run: |
          # make sure our script is executable
          chmod +x ./tools/setup_maestro.sh
          # source will install everything and activate the venv in this shell
          source ./tools/setup_maestro.sh

      - name: Run unit tests
        run: |
          poetry run pytest --ignore=tests/integration/deploys
