name: Check Mermaid

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-mermaid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv and activate the environment
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
    - name: Install dependencies
      run: |
        uv sync
    - name: Check mermaid
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        uv run tools/check-mermaid.sh
