name: Maestro Run Tests

on:
  push:
    branches: [ "main" ]
    paths:
    - '**'
  pull_request:
    branches: [ "main" ]
    paths:
    - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KUBERNETES_TEST: 1
      DEPLOY_DOCKER_TEST: 1
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Kind
      run: |
        curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-$(uname)-amd64"
        chmod +x ./kind
        sudo mv kind /usr/local/bin
        which kind
    - name: Create Kind cluster
      run: |
        kind create cluster --config tests/integration/deploys/kind-config.yaml 
    - name: Install uv and activate the environment
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
    - name: Install dependencies
      run: |
        uv sync --all-extras
    - name: Check code format and style
      run: |
        uv run ruff check
        uv run ruff format --check
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        uv run pytest -v -rA
